jai:
  tempfolder: C:\\temp\\JAI_TEMP

# Define a custom port instead of the default 8080
server:
  port: 8080
  # The format used for the keystore
  ssl:
    #key-store-type: PKCS12
# The path to the keystore containing the certificate
    key-store: C:\\Program Files\\Java\\jdk1.8.0_31\\bin\\keystore.jks
# The password used to generate the certificate
    key-store-password: changeit
# The alias mapped to the certificate
    key-alias: tomcat
# Tell Spring Security (if used) to require requests over HTTPS
security:
  require-ssl: true
# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2
# Datasource
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver